### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by emipta** [Taiko2k/tauonmb#10]
Thanks for your work, i love it Tauon

Tauon is perfect now, It would be amazing add search bar or similar for search the music.

Apologies for my english.

**Comment by emipta** [comment]
Yeah, thanks a lot! 

![captura de pantalla de 2018-08-30 13-24-57](https://user-images.githubusercontent.com/37155732/44848740-36b91980-ac58-11e8-981d-7d183e42561f.png)

**Comment by Taiko2k** [comment]
Cool! Thank you for your kind words.
