### ISSUE TITLE
[Arch Linux] Can't run the pogram (installed from AUR)

### ISSUE THREAD

**Issue by ArneDJ** [Taiko2k/tauonmb#13]
I get this when I try to run "python3 /opt/tauon-music-box/tauon.py %U".
```
Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 216, in <module>
    if 'en' not in lc[0]:
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by Taiko2k** [comment]
Interesting. Looks like an issue with some locale detection, I didn't anticipate there not being one. I'll fix that in the next release.

In the mean time, do you have a locale generated on your system? Perhaps you forgot this step in the arch install guide https://wiki.archlinux.org/index.php/Installation_guide#Localization

**Comment by ArneDJ** [comment]
Just did locale-gen, I'm using en_US.UTF-8 UTF-8 if that helps. Still get the same error.

**Comment by ArneDJ** [comment]
I rebooted and the program runs now, the issue was indeed with the locale but I forgot to reboot.
