### ISSUE TITLE
Gapless playback cutting off tracks

### ISSUE THREAD

**Issue by SehWho** [Taiko2k/tauonmb#16]
I know some issues with mp3s have been mentioned, but even FLAC files are being cut off at the end instead of having true gapless playback.  I've tested the same files in other players and it's working as expected there.

**Comment by SehWho** [comment]
Don't want to directly upload music on this account, but I imagine this will be the case on any copy of this since it seems to be a problem all around for me: Meat Grinder by Madvillain.

https://streamable.com/m8uuk

**Comment by Taiko2k** [comment]
Thanks for that, I've been able to figure out the cause. The issue arises when having "Use crossfades when jumping tracks" disabled. So seems when enabled it as shown, gapless then will work.

![screenshot from 2018-11-09 14-55-16](https://user-images.githubusercontent.com/17271572/48238415-d6044500-e42f-11e8-908d-58e57b45d628.png)

I was only testing with it enabled so I never noticed.

**Comment by Taiko2k** [comment]
I've pushed out a hotfix for this. Hopefully things will be working as expected now.
