### ISSUE TITLE
"Edit With Picard" opens nothing

### ISSUE THREAD

**Issue by SehWho** [Taiko2k/tauonmb#17]
This has been the case since I started using the program, not just the most recent versions, but even with Picard installed, this option has never done anything other than show the "Picard Launched" message for me.

**Comment by Taiko2k** [comment]
That's strange...

Does launching `picard` from the terminal start the program as expected?

**Comment by SehWho** [comment]
Yes it does

**Comment by SehWho** [comment]
`Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/app/bin/tauon.py", line 10483, in editor
    complete = subprocess.run(shlex.split(file_line), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'picard'

`

**Comment by SehWho** [comment]
![selection_538](https://user-images.githubusercontent.com/18540948/48289799-5463e580-e436-11e8-8a42-d814ae914031.png)

But then, as I said, typing "picard" as usual works fine.

**Comment by Taiko2k** [comment]
I see, this is caused by the Flatpak sanboxing. Its hiding the host `/usr/bin`. I'm pretty sure it used to work, so perhaps they changed it to blocked despite setting the "filesystem=host" permission.

**Comment by Taiko2k** [comment]
I've found there is a supported way to run host commands in Flatpak. (Can be done by setting the `--talk-name=org.freedesktop.Flatpak` permission and using the `flatpak-spawn --host` command.)

Ive updated the Flatpak on the [v3.3.2 release page](https://github.com/Taiko2k/tauonmb/releases/tag/v3.3.2) with these changes. So launching Picard should work now.
