### ISSUE TITLE
Window starts unmaximized 

### ISSUE THREAD

**Issue by SehWho** [Taiko2k/tauonmb#19]
(This is using the flatpak version)

As far as I remember, this has not always been the behavior and it wasn't noted in any release notes, but for a while now the size of the window is not carried over or remembered upon opening Tauon again.  No matter what, it will start at the smallest size it can be compacted to.

![image](https://user-images.githubusercontent.com/18540948/50124235-59803580-0229-11e9-9566-62a3a1d55853.png)

**Comment by Taiko2k** [comment]
Yes this is not intended behavior. But it is working for me. Hmm... this might be a little hard to debug. 

Maybe lets test resetting the player and see if it still does it.

 1. To do this, go `MENU -> Settings... -> Function (tab) -> Open data folder (button)'
 2. Your file browser should open and you should see a file named `state.p` in that folder
 3. Close Tauon Music Box.
 4. Rename `state.p` to something else like `state.p.backup`
 5. Launch Tauon Music Box.

Does the issue persist now? (If it doesn't, you could start over with this blank state and re import your music.) 

To undo the reset:

 1. Close player
 2. Delete the new `state.p`
 3. Finally, rename our old `state.p.backup` back to `state.p`

**Comment by Taiko2k** [comment]
Maybe the desktop environment is doing it...

Try install this updated version https://github.com/Taiko2k/tauonmb/releases/download/v3.5.0/tauon-test.flatpak 

Then launch from terminal `flatpak run com.github.taiko2k.tauonmb`

The output should give us some insight

t to whats happening.

For example, I open player, resize the window, close player: (I removed some duplicate entries)

```
!!!! CREATING WINDOW WITH SIZE [1186, 600]
!!! THE WINDOW HAS BEEN RESIZED  from [1186, 600] to [1186, 602]
!!! NOTE SIZE OF WINDOW 
[1186, 602]
!!! THE WINDOW HAS BEEN RESIZED  from [1641, 782] to [1641, 783]
!!! NOTE SIZE OF WINDOW
[1641, 783]
!!! SAVE SIZE OF WINDOW
[1641, 783]
```
Then I open back up

```
!!! CREATING WINDOW WITH SIZE [1641, 783]
```

Soo, in this case I finally end up with a window size of [1641, 783] which isn't small

**Comment by SehWho** [comment]
Upon maximizing and closing:

`!!! THE WINDOW IS MAXIMIZED
!!! THE WINDOW HAS BEEN RESIZED  from [560, 330] to [1920, 1051]
!!! SIZE OF WINDOW NOT NOTED
BASS Unloaded
Writing database to disk.
!!! SAVE SIZE OF WINDOW
[560, 330]
Unloading SDL...
SDL unloaded
bye
`
Opening again:

`Creating window...
!!! CREATING WINDOW WITH SIZE [560, 330]
`

then some other stuff and

`Setup done. Entering main loop
!!! NOTE SIZE OF WINDOW
[560, 330]
`

**Comment by SehWho** [comment]
Hmm, so it looks like it's now saving it if it's resized but not maximized.  I think I remember testing that before and it not working, but maybe I'm wrong.

**Comment by Taiko2k** [comment]
I see the cause now. This is a bug.

The window is supposed to return to a maximized state when you restart. But it is not, but the player thinks it is, so does not update the window size to be saved.

I've hopefully fixed this bug now. I've updated the flatpak with this change. https://github.com/Taiko2k/tauonmb/releases/download/v3.5.0/tauon.flatpak

**Comment by SehWho** [comment]
Working now as expected, thank you!
