### ISSUE TITLE
After closing Picard, nothing resets and fields are not updated

### ISSUE THREAD

**Issue by SehWho** [Taiko2k/tauonmb#20]
(This is with the flatpak release)

After making an edit with Picard, despite saying that fields will be updated upon closing, nothing happens and the library must be manually reimported.

Also, do any of the current features allow for files added to the library folder to be automatically detected?  I thought for a while that "Monitor download folders" might do this, and was broken, but I just actually read the documentation and realized that it doesn't do what I thought.  So I still have to manually re-import every time I download something.

**Comment by SehWho** [comment]
After closing Picard but before re-importing, if I try to play the files, they will grey out and it will skip to whatever's next up like any other time files are modified or deleted.  Also, near as I can tell, "Reload Metadata" doesn't do anything.  So if I use it in the situation we're talking about here on the greyed out tracks, nothing happens.

Since Tauon is sorta built around keeping a nicely managed library on your own, I normally manually put newly downloaded music into its spot in my music folder, rather than keeping it in a temporary location.  So at least for how my flow goes, just watching the folder that's added to the library would be enough.

**Comment by Taiko2k** [comment]
Ah, I see.

I'm guessing Picard is changing the file names. You likely have this setting on:

![rename](https://user-images.githubusercontent.com/17271572/50129890-fa312c80-02df-11e9-9f74-dcce4d1cc17e.jpg)

And Tauon is losing track of the files. 

Its supposed to read these file changes from the debug output, but perhaps this format is different in older versions. What version of Picard are you using? I'm using `2.0.4`

Anyway, unticking that setting should fix it.

**Comment by SehWho** [comment]
So if I turn that off it will still change the title field of the tags, but not the names of the files themselves?  I'll try that.  I am on an older version, 1.4.2 at the moment.

**Comment by SehWho** [comment]
Looks like it works as intended with that setting off, thanks!

**Comment by Taiko2k** [comment]
As for the folder monitoring issue.. I'm trying to think of a good way of solving this...

I'm curious, is your music folder the standard one in your home folder? `~/Music`

**Comment by SehWho** [comment]
Yes, I use that with artist folders then albums within those.  I don't really use the separate library features that this supports.

**Comment by Taiko2k** [comment]
I've added a sync folder feature. It's not automatic but fairly simple. Hopefully its an adequate solution to this problem. And I hope its not too un-intuitive as to how it works. Let me know what you think.
