### ISSUE TITLE
"Folder Purge Embedded" can't strip album art on FLAC files

### ISSUE THREAD

**Issue by SehWho** [Taiko2k/tauonmb#21]
I thought I read somewhere that purging album art from FLAC files would cause an issue, but I can't find it anywhere in the current documentation or known issues so I'm going to assume I made that up and open this issue.  Sorry if I'm just missing it!

The name should be pretty self-explanatory, I can't purge embedded album art when they're on FLAC files.

**Comment by Taiko2k** [comment]
Only MP3 is currently supported with this feature. I'll look into adding it for FLAC.

**Comment by Taiko2k** [comment]
I have this working now. Will be available in next release.
