### ISSUE TITLE
Scrobble "Album Artist" rather than "Artist"?

### ISSUE THREAD

**Issue by SehWho** [Taiko2k/tauonmb#22]
Sorry for the 4th issue in a row here, but this is a pretty big deal imo:

As it is, Tauon seems to ignore the Album Artist field entirely in favor of just grouping by folder and relying on artist.  This works fine, but when scrobbling to Last.fm it causes issues.  The most preferred way to display tags (as MusicBrainz formats it) puts featured artists in the Artist field rather than the track title, which is displayed nicely in the player but when it passes on scrobbles it creates a big mess, as Last.fm will typically treat this as an entirely separate artist of its own, creating a giant mess and ruining stats.

![image](https://user-images.githubusercontent.com/18540948/50132091-f1dae200-024a-11e9-84e8-29104b68287a.png)

Other clients fix this by adding an option to scrobble with Album Artist rather than Artist, would that be a possibility here?

**Comment by Taiko2k** [comment]
Yes I see what you mean.

However other times this would not be wanted, such as with compilation albums where using the album artist would not make sense.

Perhaps a solution would be to detect the word `feat.` in the artist field and only then submit the album-artist. Looking through my music library it seems like this would be the optimal for cases.

**Comment by SehWho** [comment]
Yeah, maybe if you could get together all the different ways to display featured artists.  I know commas and semicolons are also used fairly often.  

Just speaking for myself, a toggle for album artist scrobbling would be preferable though either way would be a huge improvement.
