### ISSUE TITLE
Pause Fade-in/Fade-out times don't work?

### ISSUE THREAD

**Issue by Clleb** [Taiko2k/tauonmb#23]
(using the flatpak version)
Hi, I don't really know if I'm doing this the wrong way or something, but in the config file I've tried to change both the #pause-fade-time and #cross-fade-time values to a number of different things (0, 1, 100, -1, -100, etc) to try and disable the fade-in/fade-out when you pause/play a song and cross-fade in general, but changing these values didn't really seem to do anything. Not sure if I've just missed another setting for it or if I've just not put in the correct value.
![image](https://user-images.githubusercontent.com/45979212/50182130-1a5aee80-02d4-11e9-9bc6-0e58f665afb7.png) - values in config.ini currently.

These are my other settings, I think I've managed to get crossfade off through this but fade-in/out on pause and play is still present.
![image](https://user-images.githubusercontent.com/45979212/50182219-6312a780-02d4-11e9-8182-d12b1fe1d674.png)

**Comment by Taiko2k** [comment]
I actually used to have this wording in the config file, but it seems I must have removed it.

```
# --- Playback / Audio --------------------------------------------------------
# Fade times in ms. Full gapless playback not supported (min 50ms, max 3000ms)

pause-fade-time=400
cross-fade-time=700
```

The current minimum value it will accept is 51.

Though indeed there should be an option to disable the play/pause fade entirely. I will add this setting in the next release.
