### ISSUE TITLE
Calculate folder's full playtime?

### ISSUE THREAD

**Issue by Clleb** [Taiko2k/tauonmb#24]
This is a really minor thing to want, but it'd be nice if you could toggle to see the full playtime of all songs in a folder added together. 

Not sure how feasible it is without looking awkward but maybe shifting the top Album - Artist - Year bar contents to the left a bit and showing full time to the right (top red, looks kinda awkward when drawn but i tried) or maybe making an extra dummy bar at the end of a list that just shows total playtime (bottom red)
![selection_016](https://user-images.githubusercontent.com/45979212/50183775-af5fe680-02d8-11e9-9b5f-cc9485c452e4.jpg)

**Comment by Taiko2k** [comment]
Indeed it is something I have thought about, but I wasn't sure where or how to add it.

But as you say, perhaps it could go next to the title. Heres what I got:

![ablumtime2](https://user-images.githubusercontent.com/17271572/50189410-fa860200-0389-11e9-93d1-ce04de8467f5.png)

I think it looks alright. What do you think? I would add an option in settings to show this.

**Comment by Clleb** [comment]
I like it! It might look a bit off to some people because it's shifted over 1 character from the lineup of the other times, but that's not a big deal at all and I personally don't mind it.

**Comment by Taiko2k** [comment]
I hadn't thought about it lining up. But yeah I don't mind it like this either. Would be a headache to deal with anyway.

I've added the option in now. Will be available in the next release.

Btw if you didn't know already, you can also view the total time by clicking to cycle the time indicator.

![totaltime](https://user-images.githubusercontent.com/17271572/50192678-260fe900-0398-11e9-86b9-3956b54e0193.png)
