### ISSUE TITLE
[Archlinux] Can`t click buttons after back from minimized

### ISSUE THREAD

**Issue by tyzmodo** [Taiko2k/tauonmb#3]
it seems that the application can`t get any focus unless you adjust the boarder.

**Comment by Taiko2k** [comment]
I can't seem to replicate. Actually try run these and see if that fixes it:

    $ sudo pacman -S sdl2
    $ sudo pip3 install pysdl2 --upgrade

If not, could you tell me what DE you're using?

**Comment by Taiko2k** [comment]
Never mind, I was able to replicate the issue in Ubuntu and found the problem. I've pushed out an update.

**Comment by tyzmodo** [comment]
Thank you!
