### ISSUE TITLE
random album playback?

### ISSUE THREAD

**Issue by legion1978** [Taiko2k/tauonmb#4]
my friend, only one look at this player and i completely fell in love. its simply gorgeous and has some features i asked in the past to other players developers. well done. im reading the docs but so far i cant find random album playback.. is it not available? meanwhile ill setup some playlists :v thnks!

**Comment by Taiko2k** [comment]
Thanks for the feedback! Glad to hear it made a good first impression.

So for random albums, once you have a playlist, right click the playlist's tab at the top, select "Sort..." and try "Shuffled Folders". This will create a new shuffled playlist, hopefully that fulfils what you're looking for.

**Comment by legion1978** [comment]
yes this should do it ^^ thank you. im still going through the options and testing. neat.

**Comment by Taiko2k** [comment]
Cool. Let me know if you have any other questions or come across any issues.

**Comment by legion1978** [comment]
actually i was wondering about the lyrics functions. should i write here or open a new thread about it?

**Comment by Taiko2k** [comment]
Just here is fine.
