### ISSUE TITLE
Can't get it working on Mint

### ISSUE THREAD

**Issue by LightningStalker** [Taiko2k/tauonmb#6]
I followed all the instructions in setup.md and it complains about not finding the libraries. It says to copy the directories from cairo hsaudiotag and stagger into the tauon directory from what I understand but that doesn't work. Copying the files in those directories into the tauon directory gets closer to working but it still quits with this error:

    $ python3 tauon.py 
    Tauon Music Box
    v2.6.2
    Copyright 2015-2017 Taiko2k captain.gxj@gmail.com

    Running in portable mode
    Install directory: /home/*****/src/tauon-music-box
    Traceback (most recent call last):
      File "tauon.py", line 212, in <module>
        from hsaudiotag import auto
    ImportError: No module named 'hsaudiotag'

**Comment by Taiko2k** [comment]
You would need to make sure to copy the inner 'hsaudiotag' folder. So the one with `__init__.py` in it, not the one with `setup.py`. I admit, the instructions there are a bit vague, and they were missing some information which I've just added. 

But anyhow, to try make things easier I've thrown together a .deb file, hopefully that just works. (Haven't tested it on another machine)

https://github.com/Taiko2k/tauonmb/releases/download/v2.6.2/tauonmusicbox_2.6.2-1.deb

**Comment by LightningStalker** [comment]
Ok I installed it, but it's not seeing the modules in the subdirectories.

$ python3 tauon.py
Tauon Music Box
v2.6.2
Copyright 2015-2017 Taiko2k captain.gxj@gmail.com

    Running from installed location
    User files and config location: /home/robert/.tauonmb-user
    Install directory: /opt/tauon-music-box
    Traceback (most recent call last):
      File "tauon.py", line 244, in <module>
        import cairo
      File "/opt/tauon-music-box/cairo/__init__.py", line 1, in <module>
        from ._cairo import *  # noqa: F401,F403
    ImportError: No module named 'cairo._cairo'

**Comment by Taiko2k** [comment]
I was afraid of that. Ok try delete that Cairo folder
'/opt/tauon-music-box/cairo' and replace it with the one you built.
'Cairo/build/lib.linux-x86_64-36/cairo'

If that doesn't work, I'll be out of ideas for now.  I'll assume the
packages of Mint aren't new enough yet.

**Comment by LightningStalker** [comment]
It almost loads then quits with this error

    $ python3 tauon.py 
    Tauon Music Box
    v2.6.2
    Copyright 2015-2017 Taiko2k captain.gxj@gmail.com

    Running from installed location
    User files and config location: /home/****/.tauonmb-user
    Install directory: /opt/tauon-music-box
    No existing star.p file
    Error loading save file
    warning: error loading settings
    Could not connect to gnome media keys
    Bass library initialised
    Using SDL verrsion: 2.0.4
    Applying default theme: Mindaro
    Traceback (most recent call last):
      File "tauon.py", line 18573, in <module>
        playlist_render.full_render()
      File "tauon.py", line 15054, in full_render
        "Playlist is empty", colour, 213, bg=colours.playlist_panel_background)
      File "tauon.py", line 5263, in draw_text
        return cairo_text.draw_text_cairo(location, text, colour, font, max, bg, align)
      File "tauon.py", line 5048, in draw_text_cairo
        surf = cairo.ImageSurface.create_for_data(data, cairo.FORMAT_RGB24, w, h)
    NotImplementedError: Surface.create_for_data: Not Implemented yet.

**Comment by Taiko2k** [comment]
You must have copied the `cairo` folder wrong. I've tired it myself, that worked but I've now run into more problems. Indeed, Mint does seem to have old packages. I've put together a revised .deb file.

https://github.com/Taiko2k/tauonmb/releases/download/v2.6.2/tauonmusicbox-mint_2.6.2.-1.deb

We'll need to remove the old one first:

`sudo apt-get remove tauonmusicbox`

and remove any leftover files:

`sudo rm -r /opt/tauon-music-box`

and install the new deb. That should hopefully work. The command to run manually is now:

`PYSDL2_DLL_PATH=/opt/tauon-music-box/lib python3 /opt/tauon-music-box/tauon.py`

I've updated the desktop entry to include this.

**Comment by LightningStalker** [comment]
I see what I did now. I accidentally copied `temp.linux-x86_64-3.5` instead of `lib.linux-x86_64-3.5`. Your updated deb is working though the icon isn't showing up in my menu now for some reason. Thanks.
