### ISSUE TITLE
Doesn't save configuration

### ISSUE THREAD

**Issue by hashkeks** [Taiko2k/tauonmb#7]
Well, the problem is very simple:
I'm using the current version of Tauon Music Box on Arch, installed using AUR and it works good. The only problem is, that it doesn't save the audio output and the layout configuration which I have to manually set each time I start Tauon and after some time it's a little bit annoying. 
I start Taoun by simply executing the tauon.py with python3 which doens't give any errors.
Am I overseeing something or do I have to write settings manually into some config file?
I hope I am not totally blind this time :D

**Comment by Taiko2k** [comment]
Yes those are known issues! 
I've just been lazy about fixing them :stuck_out_tongue_winking_eye:. I should get around to sometime now that you've reminded me.
Out of curiosity what layout is it that you prefer to use?

**Comment by hashkeks** [comment]
Well, glad I reminded you :p 
Currently I'm switching between Tracks + Gallery and Art + Tracks, but I think I will stick with the first one :D

**Comment by Taiko2k** [comment]
Good to hear you prefer that one since I'm planning on removing the Art + Tracks view. I'm hoping no one will miss it.

**Comment by hashkeks** [comment]
Let's hope so. May I ask if you want to replace it with another layout or remove it completely? If the latter one is the case I'm wondering for what use :)

**Comment by Taiko2k** [comment]
Completely, along with the 'gallery only' view. I felt these two were kind of redundant and simplifying things might improve the user experience. Heres what my latest prototype looks like:
![screenshot from 2018-03-02 13-10-47](https://user-images.githubusercontent.com/17271572/36876748-4f2406e0-1e1b-11e8-8536-c67b2e67344a.png)
Much simpler!

**Comment by hashkeks** [comment]
Indeed looks good. Is the next update going to have more optical changes or also functional ones?

**Comment by Taiko2k** [comment]
Just small fixes. I don't have anything major planed, but I'm open for ideas. Figuring out how to elegantly integrate features into the UI and workflow can be difficult.

**Comment by hashkeks** [comment]
Well, I too don't really know what to improve. The only thing missing for me is that I can't pause/play with space :D

**Comment by Taiko2k** [comment]
Forgot to close this. The original issue should be solved in the latest release. 

I've added space-bar for play and pause for the next release, whenever that may be.
