### ISSUE TITLE
Crossfader Toggle

### ISSUE THREAD

**Issue by SehWho** [Taiko2k/tauonmb#9]
Can there be some way to disable the crossfader, if there aren't going to be any options to configure it?  I actually adore it when finding something to play and skipping between different things, but it hurts album listening more than normal playback with gaps would.

**Comment by Taiko2k** [comment]
If I think about it, crossfading when switching tracks would mean that the very start of a song would always be cut off. I believe this is what you mean? I agree that is an issue.

I've added an option to turn this off. It seems to work well, so I'll probably set this as the new default behaviour too.

![screenshot from 2018-08-30 13-44-44](https://user-images.githubusercontent.com/17271572/44824973-6538f380-ac5c-11e8-8915-9a37d9ebde61.png)

**Comment by SehWho** [comment]
Thanks, this seems great even if it will create more of a want for gapless playback :P 

Also (probably not worth its own issue because I have no useful information): I have no idea if it's possible for you to even push anything to releases not from the AUR, but I'm suddenly getting crashes on starting Tauon, both when I tried 3.1.2 and 3.2.0 (on Mint 19).  I'm going to try restoring a snapshot from yesterday, but I thought it'd be worth mentioning.

**Comment by Taiko2k** [comment]
I've added another option to toggle ending crossfades off too. But it does produce a bit of a gap. Unfortunately I've had trouble getting gapless to work, so unfortunately its kind of off the table for now.

As for the crashes, the window outline appears but it just freezes and stops responding right? I'm getting that too now. Ill look into it...

**Comment by SehWho** [comment]
Yup that's exactly the issue.  I did my rollback and everything is working fine so I'm assuming it's a problem with this X11 update I forgot about.
![image](https://user-images.githubusercontent.com/18540948/44883675-8fe77400-ac7d-11e8-9e14-b2fdd1a1b5ed.png)

I dunno if that helps or not with finding the problem, but it's at least a band aid on my end.

**Comment by SehWho** [comment]
The problem popped up again after a while without updating X11, so maybe ignore me on that.

**Comment by Taiko2k** [comment]
It appears to be an issue the Flatpak runtime updating. So the issue will probably come back if it updates itself again. So there probably isn't any use in holding your system packages from updating. I've raised an issue and am waiting to hear back.

**Comment by Taiko2k** [comment]
I've pushed out a new release. Hopefully this solves both of those issues.
